### ISSUE TITLE
Finish the section 3. from the syllabus

### ISSUE THREAD

**Issue by arti1221** [TIS2022-FMFI/web-backups#10]
Finish the section 3 from the specification

**Comment by arti1221** [comment]
TODO:
After adding collegue **yarvelian** to the repository, please assign him and cooperate on this task.

**Comment by arti1221** [comment]
This task reffers to: https://github.com/TIS2022-FMFI/web-backups/issues/6

**Comment by Yarvelian** [comment]
Status changed to "Done"

**Comment by yarvelian** [comment]
Status changed to "Done".
