### ISSUE TITLE
Action Point

### ISSUE THREAD

**Issue by arti1221** [TIS2022-FMFI/web-backups#11]
This task is created to track the ongoing progress and newly created tasks. Please, after creating any task or changing it's status -> track the work here so we can have a better overview of the job progress.

**Comment by arti1221** [comment]
Newly created tasks:
https://github.com/TIS2022-FMFI/web-backups/issues/10
https://github.com/TIS2022-FMFI/web-backups/issues/9
https://github.com/TIS2022-FMFI/web-backups/issues/8
https://github.com/TIS2022-FMFI/web-backups/issues/7
https://github.com/TIS2022-FMFI/web-backups/issues/6

**Comment by arti1221** [comment]
Newly created tasks:
https://github.com/TIS2022-FMFI/web-backups/issues/11
https://github.com/TIS2022-FMFI/web-backups/issues/12

**Comment by arti1221** [comment]
Newly created tasks:
https://github.com/TIS2022-FMFI/web-backups/issues/13
https://github.com/TIS2022-FMFI/web-backups/issues/14

Additional info:
Please, make sure to attach the required files/documents to the repository (if it is required by the task).

**Comment by yarvelian** [comment]
Issue #10 : Status changed to "Done"

**Comment by yarvelian** [comment]
Issue #8  : Status changed to "Done"

**Comment by yarvelian** [comment]
Issue #7  : Status changed to "Done"

**Comment by yarvelian** [comment]
Issue #9  : Status changed to "Done"

**Comment by yarvelian** [comment]
Issue #12  : Status changed to "Done"

**Comment by yarvelian** [comment]
Issue #6  : Status changed to "Done"

**Comment by arti1221** [comment]
Closing the task as it is unnecessary to keep track of tasks with this kind of logic.
