### ISSUE TITLE
Review the document specification

### ISSUE THREAD

**Issue by arti1221** [TIS2022-FMFI/web-backups#12]
Please, **everybody** make a **REVIEW** of the work done by other collegues and finish the document specification. 
Task https://github.com/TIS2022-FMFI/web-backups/issues/6 can be closed only after the review is finished, otherwise it will be reopened!

**Comment by arti1221** [comment]
Reviewed and added comments in the doc.

**Comment by yarvelian** [comment]
All team members reviewed the finished document. 
The history of the creation and editing of the document can be seen [here](https://docs.google.com/document/d/17XWqm6eay-SICVFn8XCsEBsyc-x2DxKq/edit?usp=sharing&ouid=114339219100475102964&rtpof=true&sd=true).

**Comment by yarvelian** [comment]
Status changed to "Done".
