### ISSUE TITLE
Create full notes from the meeting with the sponsor-pt.3

### ISSUE THREAD

**Issue by M4jo** [TIS2022-FMFI/web-backups#13]
Please create notes from the meeting from 11.10.

**Comment by M4jo** [comment]
The notes have been made please review the document
[TISmeeting3.docx](https://github.com/TIS2022-FMFI/web-backups/files/9774668/TISmeeting3.docx)
Assignee: omaksi since the project leader is not avaiable yet

**Comment by arti1221** [comment]
This task reffers to: https://github.com/TIS2022-FMFI/web-backups/issues/14
