### ISSUE TITLE
Výsledný katalóg požiadaviek, ktorý odsúhlasil zadávateľ

### ISSUE THREAD

**Issue by omaksi** [TIS2022-FMFI/web-backups#5]
Výsledný katalóg požiadaviek, ktorý odsúhlasil zadávateľ. Kým mal zadávateľ pripomienky, treba ich najskôr zohľadniť a ponúknuť mu na odsúhlasenie aktualizovanú, vylepšenú verziu. Pred tým, ako sa posiela návrh katalógu požiadaviek zadávateľovi, ho musí schváliť cvičiaci.

**Comment by arti1221** [comment]
There was a new issue created for this problem. The specification must pass the ongoing review by all developers.
Link: 
https://github.com/TIS2022-FMFI/web-backups/issues/6

Due of this I'm closing this issue.

Best wishes and kindest regards
Filip

**Comment by pavelpetrovic** [comment]
It seems you have orverorganized this.
First of all, this issue is not part of your project - make sure ALL issues are assigned in the project, otherwise they cannot be seen there. 
Next, you closed both issues related to Requirements Specification, but I have not been notified and mostly I have not read and approved the final version. 
Kindly keep one issue related to Requirements Specification open until it is approved first by your "cviciaci" and then your "zadavatel". :-) 
Thanks.

**Comment by pavelpetrovic** [comment]
Moje stručné komentáre:
 * v 2.2. je "backup and store" mysleli ste "backup and restore"?  Rozpísal by som to do dvoch viet, aby to bolo zrozumiteľnejšie.
 * do 2.5. mozete pridat. "Application will always ask the user before overwriting any existing data" for confirmation with a clear explanatory message what it is going to do.
 * 3.1.3.2 Output a list of backups for each site => nejednoznacnost - da sa to urobit tak, ze vypise vsetky backupy vsetkych sajtov, alebo vsetky backupy urceneho. hlasujem za druhu moznost, v tom pripade napr. "for a specified site"
 * 3.1.3.3 toto nie je zrozumitelne, preco remote server potrebuje tuto notifikaciu. prosim vysvetlit, a/alebo pridat krizovu referenciu
 * 3.1.3.4 to iste. myslim, ze sme hovorili skor o disablovani/enablovani ako o deletovani suboru. mozno bude najjednoduchsie to urobit tak, ako to robi konfig apache webservra: ten ma adresare sites-enabled a sites-available. prvy len obsahuje linky na subory v druhom. tie tam mozu byt, aj ked su neaktivne. len tie, co su aktivne maju v enabled linky.
 * 3.1.3.5. prosim pridat "at any time" na koniec
 * 3.1.7.2 prosim upresnit. bolo by dobre aby to fungovalo rekurzivne. t.j. ak sa urci nejaky folder, tak to plati pre vsetky podfoldre. tiez tie wildcardy by mali matchovat aj foldre, cize napr. nazalohovat/* by malo matchnut aj vsetky foldre vnutri foldra nezalohovat/
 * 3.1.7.3 tu by mal fungovat rovnaky rezim ako 3.1.7.2, treba to uviest, inak je to nejednoznacne.
 * 3.1.7.6 a 7: prosim doplnit: if the script returns nonzero exit code, the backup will not procede
 * prosim pridat na koniec funkcnych poziadaviek, ze aplikacia robi do jedneho textoveho suboru log, kde zapisuje vsetky hromadne akcie (vtedy sa robil backup, taky onaky, restore a pod), ktore system robil. tento log je iba lokalny, tento log bude ulozeny na nejakom mieste, kde su aj konfigy. okrem toho z kazdeho jedneho backup alebo restore vytvara samostatny podrobny log so vsetkymi subormi, ktore sa odzalohovali/restorovali. tiez na tom istom mieste.
 * 3.1.10 nie je gramaticky ok english sentence, ale napisal by som tam, ze nielen na povodne miesto, ale aj na ine urcene miesto, ked tak pouzivatel zada
 * 3.1.7.8 "That means to keep one backup that is n days old"  - at least n days old, a na koniec tej vety prosim pridat "for each specified category"
 * niekde (podla mna niekde v casti 2) este treba uviest, ze Vas system neriesi, kedy sa ktory backup robi (inkrementalny, uplny) a predpoklada sa, ze to pouzivatel nastavi pomocou nejakeho externeho nastroja, napr. cron.
 
 skuste to, prosim, poupravovat a poslat zadavatelovi :-), ci bude s vyslednym katalogom suhlasit, alebo mu napadnu este nejake upravy. dakujem.

**Comment by omaksi** [comment]
Adresovali sme komentare a doplnili do dokumentu v #16 
Prosim pozrite @pavelpetrovic ci je to uz teraz akceptovatelne.

**Comment by arti1221** [comment]
Task finished.
